image: node:lts

stages:
  - prepare
  - build
  - publish

cache:
  untracked: true
  paths:
   - node_modules/

Install Dependencies:
  stage: prepare
  script:
    - npm install

Build App:
  stage: build
  script:
    - npm run build

Publish Docker:
  stage: publish
  image: docker:stable
  script:
    - export IMAGE_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
        --pull
        --cache-from $CI_REGISTRY_IMAGE:latest
        --tag $CI_REGISTRY_IMAGE:$IMAGE_TAG
        --tag $CI_REGISTRY_IMAGE:latest
        --build-arg VCS_REF=$CI_COMMIT_SHA
        --build-arg VCS_URL=$CI_PROJECT_URL .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest